### ISSUE TITLE
interested in using/contributing

### ISSUE THREAD

**Issue by mumbel** [mumbel/ghidra_we#1]
@sethm  came across a twitter post, hadn't every heard of this processor and it looked semi-interesting.  I hadn't implemented a variable length instruction set in sleigh yet, so I gave it a go today since it didn't look too large of an ISA.  Lots of stuff is still wrong, but the larger parts are mostly done or coming together.  The bigger items are cleaning up `addrmode` tables and the cspec and pspec files.  I don't think I'll get much further since I'll probably not get too familiar with the processor, but if you have any issues I could probably take a look if you're interested in this.   Also PRs are welcome, or I can just add you as a contributor.

**Comment by sethm** [comment]
Wow, I'd love to help! I've been doing a ton of work around the WE32000 family of processors for the last few years. My main barrier I think has been an unfamiliarity with the internals of Ghidra (though I have used it to reverse some x86 stuff).

Let's work with PRs for now, and you can add me as a contributor if that feels easier.

**Comment by mumbel** [comment]
Sounds good.
